version: "2"

services:
  vote:
    build: ./vote
    command: python app.py
    ports:
      - "80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker

  db:
    image: postgres:9.4

  result:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "80"
      - "5858"

