version: "2"

services:
  vote-app:
    build: ./vote
    command: python app.py
    ports:
      - "80"
    networks:
      voteapp:
      environment:
  	- "constraint:node==app-node2"
    labels:
         interlock.hostname: "vote"
         interlock.domain:   "example.com"

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      voteapp:
    container_name: redis
  worker:
    build: ./worker
    networks:
      voteapp:
        aliases:
         - workers

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      voteapp:
    container_name: db


  result-app:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "80"
      - "5858"
    networks:
      voteapp:
      environment:
          - "constraint:node==app-node2"
    labels:
         interlock.hostname: "results"
         interlock.domain:   "example.com"

volumes:
  db-data:

networks:
  voteapp:
